package com.hand.hcf.app.mdata.utils;

/**
 *
 */
public interface RespCode {

    /**
     *  成功
     */

    String SYS_ID_NOT_NULL = "SYS_ID_NOT_NULL";

    String SYS_ID_NULL = "SYS_ID_NULL";

    String SUPPLIER_MARK_NOT_EXIST = "SUPPLIER_MARK_NOT_EXIST";

    String SUPPLIER_CODE_EXISTS = "SUPPLIER_CODE_EXISTS";

    String SUPPLIER_NAME_EXISTS = "SUPPLIER_NAME_EXISTS";

    String SUPPLIER_BANK_ACCOUNT_REPEAT = "SUPPLIER_BANK_ACCOUNT_REPEAT";

    String SUPPLIER_BANK_ACCOUNT_WAS_OCCUPIED = "SUPPLIER_BANK_ACCOUNT_WAS_OCCUPIED";

    String SUPPLIER_NOT_EXIST = "SUPPLIER_NOT_EXIST";

    /** 请求服务[{0}]时异常! */
    String SUPPLIER_CALL_METHOD_ERROR = "SUPPLIER_CALL_METHOD_ERROR";
    /** 系统错误，请联系管理员! */
    String SYS_ERROR = "SYS_ERROR";

    String SYS_YES = "sys.yes";//是
    String SYS_NO = "sys.no";//否
    String SYS_ENABLED = "sys.enabled";//启用
    String SYS_DISABLED = "sys.disabled";//禁用
    String SYS_GENDER_MAN = "sys.gender.man";//男
    String SYS_GENDER_WOMAN = "sys.gender.women";//女
    String SYS_GENDER_UNKNOWN = "sys.gender.unknown";//未知
    String SYS_REQUEST_RESOURCE_COULD_NOT_BE_FOUND="SYS_REQUEST_RESOURCE_COULD_NOT_BE_FOUND";//找不到请求的资源！


    String CODE_CANT_CHINESE="6057001";//编码不能包含汉字
    String CODE_CANT_ILLEGAL="6057002";//编码不能包含非法字符
    String CODE_LENGTH_LT_36="6057003";//编码长度不能超过36位
    String CODE_CANT_MODIFIED="6057004";//编码不允许修改

    String READ_FILE_FAILED = "7005";    //读取文件失败

    /**
     * 供应商类型维护
     */
    String SUPPLIER_NON_GROUP_AUTHORITY = "SUPPLIER_NON_GROUP_AUTHORITY";
    String SUPPLIER_TYPE_CODE_EXISTS = "SUPPLIER_TYPE_CODE_EXISTS";
    String SUPPLIER_TYPE_CODE_INPUT_ERROR = "SUPPLIER_TYPE_CODE_INPUT_ERROR";
    String SUPPLIER_TYPE_NAME_INPUT_ERROR = "SUPPLIER_TYPE_NAME_INPUT_ERROR";
    String SUPPLIER_TYPE_NOT_EXISTS = "SUPPLIER_TYPE_NOT_EXISTS";
    String SUPPLIER_TYPE_NAME_AND_CODE_BOTH_EXIST = "SUPPLIER_TYPE_NAME_AND_CODE_BOTH_EXIST";
    String SUPPLIER_TYPE_NAME_EXISTS = "SUPPLIER_TYPE_NAME_EXISTS";

    /**
     * 供应商信息维护
     */
    String SUPPLIER_TYPE_EMPTY = "SUPPLIER_TYPE_EMPTY";
    String SUPPLIER_CHARACTER_FORMAT_ERROR = "SUPPLIER_CHARACTER_FORMAT_ERROR";
    String SUPPLIER_NAME_NOT_BLANK_AND_LENGTH_NO_MORE_THAN_50 = "SUPPLIER_NAME_NOT_BLANK_AND_LENGTH_NO_MORE_THAN_50";
    String SUPPLIER_NOT_EXISTS = "SUPPLIER_NOT_EXISTS";
    String SUPPLIER_DATA_SOURCE_IDENTIFIER_EMPTY = "SUPPLIER_DATA_SOURCE_IDENTIFIER_EMPTY";
    String SUPPLIER_NAME_EXISTS_IN_COMPANY_OR_TENANT_LEVEL = "SUPPLIER_NAME_EXISTS_IN_COMPANY_OR_TENANT_LEVEL";
    String SUPPLIER_MULTIPLE_ID_DATABASES = "SUPPLIER_MULTIPLE_ID_DATABASES";
    String SUPPLIER_MULTIPLE_NAME_DATABASES = "SUPPLIER_MULTIPLE_NAME_DATABASES";
    String SUPPLIER_NOT_EXIST_UNDER_CURRENT_TENANT = "SUPPLIER_NOT_EXIST_UNDER_CURRENT_TENANT";
    String SUPPLIER_MULTIPLE_EXIST_UNDER_CURRENT_TENANT = "SUPPLIER_MULTIPLE_EXIST_UNDER_CURRENT_TENANT";
    String SUPPLIER_LACK_OF_COMPANY_AUTHORITY = "SUPPLIER_LACK_OF_COMPANY_AUTHORITY";
    String SUPPLIER_LEGAL_REPRESENTATIVE_INOUT_ERROR = "SUPPLIER_LEGAL_REPRESENTATIVE_INOUT_ERROR";
    String SUPPLIER_TAX_NUMBER_INOUT_ERROR = "SUPPLIER_TAX_NUMBER_INOUT_ERROR";
    String SUPPLIER_CONTACT_INOUT_ERROR = "SUPPLIER_CONTACT_INOUT_ERROR";
    String SUPPLIER_CONTACT_NUMBER_INOUT_ERROR = "SUPPLIER_CONTACT_NUMBER_INOUT_ERROR";
    String SUPPLIER_EMAIL_INOUT_ERROR = "SUPPLIER_EMAIL_INOUT_ERROR";
    String SUPPLIER_FAX_INOUT_ERROR = "SUPPLIER_FAX_INOUT_ERROR";
    String SUPPLIER_ADDRESS_INOUT_ERROR = "SUPPLIER_ADDRESS_INOUT_ERROR";
    String SUPPLIER_REMARK_INOUT_ERROR = "SUPPLIER_REMARK_INOUT_ERROR";
    String SUPPLIER_COMPANY_CODE_NOT_EXIST = "SUPPLIER_COMPANY_CODE_NOT_EXIST";
    String SUPPLIER_CODE_EXISTS_AND_TRY_AGAIN = "SUPPLIER_CODE_EXISTS_AND_TRY_AGAIN";

    String SUPPLIER_VENDOR_STATUS= "SUPPLIER_VENDOR_STATUS";//供应商非可操作状态

    /**
     * 银行账号信息维护
     */
    String SUPPLIER_DISABLED = "SUPPLIER_DISABLED";
    String SUPPLIER_BANK_NAME_EMPTY = "SUPPLIER_BANK_NAME_EMPTY";
    String SUPPLIER_BANK_ACCOUNT_EMPTY = "SUPPLIER_BANK_ACCOUNT_EMPTY";
    String SUPPLIER_ACCOUNT__INOUT_ERROR = "SUPPLIER_ACCOUNT__INOUT_ERROR";
    String SUPPLIER_ENABLED_MASTER_ACCOUNT_EXISTS = "SUPPLIER_ENABLED_MASTER_ACCOUNT_EXISTS";
    String SUPPLIER_ACCOUNT_REPEAT = "SUPPLIER_ACCOUNT_REPEAT";
    String SUPPLIER_ACCOUNT_EMPTY = "SUPPLIER_ACCOUNT_EMPTY";
    String SUPPLIER_ACCOUNT_IN_USED = "SUPPLIER_ACCOUNT_IN_USED";
    String SUPPLIER_LACK_OF_COMPANY_AUTHORITY_TO_UPDATE_ACCOUNT = "SUPPLIER_LACK_OF_COMPANY_AUTHORITY_TO_UPDATE_ACCOUNT";
    String SUPPLIER_BANK_ACCOUNT_NOT_MATCH = "SUPPLIER_BANK_ACCOUNT_NOT_MATCH";
    String SUPPLIER_BANK_ACCOUNT_NOT_EXISTS = "SUPPLIER_BANK_ACCOUNT_NOT_EXISTS";

    /**
     * 供应商分配公司维护
     */
    String SUPPLIER_NON_TENANT_LEVEL_TO_DISTRIBUTE = "SUPPLIER_NON_TENANT_LEVEL_TO_DISTRIBUTE";
    String SUPPLIER_NON_SUPPLIER_OR_COMPANY_TO_DISTRIBUTE = "SUPPLIER_NON_SUPPLIER_OR_COMPANY_TO_DISTRIBUTE";
    String SUPPLIER_COMPANY_ASSOCIATION_NOT_EXISTS = "SUPPLIER_COMPANY_ASSOCIATION_NOT_EXISTS";
    String SUPPLIER_HAS_ASSIGNED_A_COMPANY = "SUPPLIER_HAS_ASSIGNED_A_COMPANY";

    /**
     * 代理授权
     */
    String VEN_AUTHORIZE_NOT_EXIST = "VEN_AUTHORIZE_NOT_EXIST";

    //国际地点组
    String LEVEL_6035001 = "6035001";

    /**
     * 币种汇率
     */
    String CURRENCY_5000 = "CURRENCY_5000";
    String CURRENCY_5001 = "CURRENCY_5001";
    String CURRENCY_5002 = "CURRENCY_5002";
    String CURRENCY_5003 = "CURRENCY_5003";
    String CURRENCY_5004 = "CURRENCY_5004";
    String CURRENCY_5005 = "CURRENCY_5005";
    String CURRENCY_5010 = "CURRENCY_5010";
    String CURRENCY_5011 = "CURRENCY_5011";
    String CURRENCY_5012 = "CURRENCY_5012";
    String CURRENCY_5013 = "CURRENCY_5013";
    String CURRENCY_5015 = "CURRENCY_5015";

    String E_120712 = "120712";
    /**
     * 银行
     */
    String BANK_CODE_LT_36 = "SYS_BANK_CODE_LESS_THAN_36";  //银行代码长度不能超过36位
    String BANK_IMPORT_ENABLE_ILLEGAL = "BANK_IMPORT_ENABLE_ILLEGAL";//是否启用输入不合法！
    String BANK_CODE_MUST_NUMBER = "SYS_BANK_CODE_MUST_BE_NUMBER";  //银行代码必须是数字
    String SWIFT_CODE_LT_36 = "SYS_SWIFT_CODE_LESS_THAN_36";  //Swift代码长度不能超过36位
    String SWIFT_CODE_MUST_NUMBER = "SYS_SWIFT_CODE_MUST_BE_NUMBER";  //Swift代码必须是数字
    String BANK_CODE_EXIST = "SYS_BANK_CODE_EXIST";  //银行代码已经存在
    String BANK_BRANCH_AND_CODE_EXIST = "SYS_BANK_BRANCH_AND_CODE_EXIST"; //银行分支名称和银行代码已存在
    String BANK_CODE_NOT_NULL = "sys_bank_code_not_null";  //银行代码不能为空
    String BANK_NAME_NOT_NULL = "sys_bank_name_not_null";  //银行名称不能为空
    String BANK_BRANCH_NAME_NOT_NULL = "sys_bank_branch_name_not_null";  //银行支行名称不能为空

    String SYS_READ_FILE_ERROR = "SYS_READ_FILE_ERROR"; // 读取文件异常 to


    String MOBILE_VALIDATE_DUPLICATED_CODE = "220001";
    String UNKNOWN_ERROR="6047018";//其他未知错误

    String COMPANY_NOT_EXIST = "121301";  //公司不存在

    String LEGAL_ENTITY_HAS_BEEN_USED = "LEGAL_ENTITY_HAS_BEEN_USED"; //法人实体已经被使用,不可修改启用状态
    String LEGAL_ENTITY_NULL = "120301";     //法人为空
    String PARENT_LEGAL_ENTITY_NULL = "120304";    //父级法人为空
    String LEGAL_ENTITY_NAME_NULL = "120305";   //法人名称为空
    String TAX_PAYER_NUMBER_NULL = "120306";    //纳税人识别号为空
    String LEGAL_ENTITY_ACCOUNT_NUMBER_EXIST = "120309";//法人实体银行卡号已存在
    String USER_NOT_EXIST = "6037002";
    String USER_OID_NOT_NULL="6045004";//员工OID不能为空
    String EMAIL_IS_NULL = "6047007";//邮箱为空
    String EMPLOYEE_EXISTS = "120201";
    String EMPLOYEE_ID_EXISTS = "EMPLOYEE_ID_EXISTS"; //员工ID已存在
    String EMPLOYEE_EMAIL_EXISTS = "EMPLOYEE_EMAIL_EXISTS";
    String EMPLOYEE_PHONE_EXISTS = "EMPLOYEE_PHONE_EXISTS";

    String USER_GROUP_OID_NOT_NULL = "6043001";//创建人员组OID不为空
    String USER_GROUP_CODE_EXIST = "6043005";
    String USER_GROUP_CONDITION_NOSEQ = "6043006";//人员组规则更新没有序号
    String USER_GROUP_MULTI_CONDITION = "6043007";
    String USER_GROUP_EXIST = "6043008";//人员组已经存在
    String USER_GROUP_NOT_EXIST = "6043009";//人员组不存在

    String USER_GROUP_CONDITION_EXIST = "121508";//人员组条件属性已存在，勿重复添加
    String USER_GROUP_NAME_LENGTH_LT_50 = "121509";//人员组名称长度不能超过50位
    String USER_GROUP_DESC_LENGTH_LT_100 = "121510";//人员组描述长度不能超过100位
    String USER_GROUP_USER_NOT_NULL = "121511";//人员组添加员工不能为空
    String USER_GROUP_CODE_NOT_MODIFIED = "121512";//人员组代码不可修改
    String USER_GROUP_PERMISSSION_NOT_EXIST = "6039002";//人员权限组不存在


    String CARD_TYPE_NOT_NULL = "sys_card_type_not_null";//证件类型不能为空
    String CARD_LAST_NAME_NOT_NULL = "sys_card_last_name_not_null";//证件姓不能为空
    String CARD_OID_MUST_NULL="sys_card_oid_must_be_null";//证件OID必须为空
    String CARD_OID_NOT_NULL="sys_card_oid_cant_be_null";//证件OID不能为空
    String CARD_FIRST_NAME_NOT_NULL = "250005";//证件名不能为空
    String CARD_EXIST = "250006";//证件已存在
    String CARD_DEFAULT_NOT_DISABLE = "250008";//证件不能设置禁用默认
    String CARD_NATIONAL_NOT_EXIST = "250009";//国籍编码不存在
    String CARD_MUST_HAVE_DEFAULT = "250010";//证件必须有一张默认
    String CARD_NUM_NOT_REPEAT = "250011";//证件号不允许重复
    String CARD_TYPE_INVALID = "6047026";//证件类型不符
    String CARD_MUST_HAVE_ENABLED_DEFAULT = "CARD_MUST_HAVE_ENABLED_DEFAULT";//必须先添加一张已启用的默认证件


    String BANK_ACC_NO_NOT_NULL = "sys_bank_account_no_not_null";  //银行账户代码不能为空
    String BANK_ACC_NAME_NOT_NULL = "sys_bank_account_name_not_null";  //银行账户名称不能为空
    String SYS_BANK_ACCOUNT_IS_USED = "SYS_BANK_ACCOUNT_IS_USED"; //银行账号已被占用

    String BANK_ACC_NOT_DISABLE_DEFAULT = "sys_bank_account_not_disable_default"; //银行账户不能设置禁用默认
    String BANK_NOT_EXIST = "sys_bank_not_exist";//银行不存在
    String BANK_ACC_MUST_DEFAULT_CARD = "sys_bank_account_must_have_default_card";//银行账户必须有一张卡默认
    /**
     * 账套
     */
    String SETOFBOOKS_18001 = "6018001";
    String SETOFBOOKS_18002 = "6018002";
    String SETOFBOOKS_CODE_NULL = "6018004";  //账套为空
    String SETOFBOOKS_PERIODSETCODE_NULL = "6018005";
    String SETOFBOOKS_FCURRENCYCODE_NULL = "6018006";
    String SETOFBOOKS_18007 = "6018007";
    String SETOFBOOKS_TENANTID_NULL = "6018008";
    String SETOFBOOKS_ID_NULL = "6018009";
    String SETOFBOOKS_18010 = "6018010";
    String SETOFBOOKS_NAME_NULL = "6018011";
    String SETOFBOOKS_18012 = "6018012";
    String SETOFBOOKS_18013 = "6018013";


    /**
     * 公司
     */
    String COMPANY_6030001 = "6030001";
    String COMPANY_6030002 = "6030002";
    String COMPANY_6030007 = "6030007";

    String E_121302 = "121302";
    String E_120307 = "120307";

    String COMPANY_GROUP_27001 = "6027001";
    String COMPANY_GROUP_27002 = "6027002";
    String COMPANY_GROUP_27003 = "6027003";
    String COMPANY_GROUP_27005 = "6027005";
    String COMPANY_GROUP_27007 = "6027007";
    String COMPANY_GROUP_27008 = "6027008";
    String COMPANY_GROUP_27009 = "6027009";
    String COMPANY_GROUP_27010 = "6027010";
    String COMPANY_GROUP_27011 = "6027011";
    String COMPANY_GROUP_ASSIGN_28001 = "6028001";
    String COMPANY_GROUP_ASSIGN_28002 = "6028002";
    String COMPANY_GROUP_ASSIGN_28003 = "6028003";
    String COMPANY_GROUP_ASSIGN_28004 = "6028004";
    String COMPANY_GROUP_ASSIGN_28005 = "6028005";
    String COMPANY_GROUP_ASSIGN_28006 = "6028006";
    String COMPANY_GROUP_ASSIGN_28007 = "6028007";
    String COMPANY_GROUP_ASSIGN_28008 = "6028008";
    String COMPANY_GROUP_ASSIGN_28010 = "6028010";
    String COMPANY_LEVEL_CODE_NULL_20001 = "6020001";//公司级别code为null
    String COMPANY_LEVEL_CODE_REPEAT_20002 = "6020002";//公司级别code重复
    String COMPANY_LEVEL_NOT_FOUND_20003 = "6020003";//公司级别不存在
    String COMPANY_LEVEL_CODE_LENGTH_MORE_THEN_LIMIT_0R_NOT_INNEGAL_20004 = "6020004";//公司级别code长度超过限制或字符非法
    String COMPANY_LEVEL_DESCRIPTION_IS_NULL_20005 = "6020005";//公司级别描述为空
    String COMPANY_LEVEL_HAS_BEEN_ENABLED_6020006 = "6020006";//公司级别已被启用

    String DEPARTMENT_ALREADY_EXISTS = "120101";  //部门已存在

    String DEPARTMENT_CODE_ALREADY_EXISTS = "120107";  //部门编码已存在

    String THIS_DEPARTMENT_PATH_ALREADY_EXISTS = "6044001";             //公司已存在此部门路径
    String DEPARTMENT_HAS_SUB_DEPARTMENTS = "6044002";                  //部门存在子部门
    String DEPARTMENT_HAS_EMPLOYEES = "6044003";                        //部门存在员工
    String THIS_DEPARTMENT_NOT_EXIST = "6044004";                        //公司不存在此部门
    String DEPARTMENT_CODE_LENGTH_CANNOT_EXCEED_100_DIGITS = "6044006"; //部门编码长度不能超过100位
    String DEPARTMENT_NAME_EMPTY_OR_MORE_THEN_50_CHARACTERS = "6044007";//部门名不能为空或者超过50个字符
    String DEPARTMENT_NAME_CANNOT_BE_EMPTY_OR_CONTAIN_BAR = "32010";//部门名称不能为空或包含'|'

    String ILLEGAL_DEPARTMENT_NAME = "2006";       //部门名字不合法

    /**
     * 部门组
     */
    String DEPARTMENT_GROUP_NOT_FOUND_23001 = "6023001";//对应的部门组不存在
    String DEPARTMENT_GROUP_DELETED_23002 = "6023002";//对应的部门组已被删除
    String DEPARTMENT_GROUP_CODE_NULL_23003 = "6023003";//部门组代码为空
    String DEPARTMENT_GROUP_CODE_REPEAT_23004 = "6023004";//部门组代码重复
    String DEPARTMENT_CODE_NULL_23006 = "6023006";//部门代码为空
    String EMP_OID_IS_NULL = "6023007";//员工oid为空
    String DEPARTMENT_GROUP_DESCRIPTION_IS_NULL_23008 = "6023008";
    String DEPARTMENT_CODE_NOT_NULL_23009 = "6023009";//部门代码不能为空

    String DEPARTMENT_GROUP_DETAIL_NULL_21001 = "6021001";//部门组明细为空
    String DEPARTMENT_GROUP_DETAIL_EXIT_21002 = "6021002";//部门组明细已经存在

    /**
     * 部门职位
     */
    String DEPARTMENT_ROLE_NAME_EXISTS = "32001";//部门角色名称已存在
    String DEPARTMENT_ROLE_NAME_NOT_EXISTS = "32002";//部门角色不存在
    String DEPARTMENT_ROLE_CODE_EMPTY = "32003";//部门角色编码不能为空
    String DEPARTMENT_ROLE_CODE_LENGTH_EXCEEDS_LIMIT_OR_ILLEGAL = "32004";//部门角色编码长度超过限制或字符非法（code只能由数字组成，且长度位4-9位）
    String DEPARTMENT_ROLE_CODE_REPEAT = "32005";//部门角色编码重复
    String WRONG_START_CODE = "32008";//0,1和6开头编码为系统保留，请使用其他数字
    String DEPARTMENT_ROLE_NAME_EMPTY = "32009";//部门角色名称不能为空

    String DataFilteringUtil_29001 = "6029001";
    String DataFilteringUtil_29002 = "6029002";
    String DataFilteringUtil_29003 = "6029003";
    String DataFilteringUtil_29004 = "6029004";

    /**
     * 会计期间
     */
    String PERIOD_CODE_REPEAT = "6024001";  //一个租户下，会计期代码重复 ！
    String TENANT_ID_CANNOT_BE_EMPTY = "6024002";  //租户id 不能为空 ！
    String TOTAL_NUMBER_SHOULD_MORE_THEN_12_AND_LESS_THEN_20 = "6024003";  //期间总数应该大于等于12小于等于20！
    String PERIOD_NAME_ATTACHED_CANNOT_BE_EMPTY = "6024004";  //期间期间名称附加不能为空！

    String MONTHS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_12 = "6025002"; //月份应小于等于12!
    String QUARTER_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_4 = "6025003"; //基础应该小于等于4!
    String THE_DATE_SHOULD_BE_LESS_THAN_31 = "6025004"; //{0}月的日期从应该小于31 ！
    String THE_DATE_SHOULD_BE_LESS_THAN_30 = "6025005"; //{0}月的日期从应该小于30 ！
    String THE_DATE_SHOULD_BE_LESS_THAN_29 = "6025006"; //{0}月的日期从应该小于29 ！
    String PERIOD_ADDITIONAL_NAME_IS_EMPTY = "6025008"; //期间名附加不能为空!
    String PERIOD_ADDITIONAL_NAME_IS_TOO_LONG = "6025009"; //期间名附加长度超出预定范围!
    String ACCOUNTING_PERIOD_IS_EMPTY = "6025010"; //会计期获取为空！
    String TIME_NAME_ADDITION_CANNOT_BE_EMPTY = "6025011"; //期间名称附加不能为空 ！
    String MONTH_FROM_CANT_BE_EMPTY = "6025012"; //月份从不能为空！
    String MONTH_TO_CANT_BE_EMPTY = "6025013"; //月份至不能为空！
    String DATE_FROM_CANT_BE_EMPTY = "6025014"; //日期从不能为空 ！
    String DATE_TO_CANT_BE_EMPTY = "6025015"; //日期至不能为空！
    String QUARTER_CANT_BE_EMPTY = "6025016"; //季度不能为空！
    String DATE_MAINTENANCE_IS_INCOMPLETE = "6025017"; //日期维护不完整，请调整！

    String LAST_PERIOD_UNOPENED = "6026001"; //当前期间的上一期间未被打开，请先打开上一期间！
    String NEXT_PERIOD_UNCLOSED = "6026002"; //请先打开当前期间的后一个期间，否则当前期间无法重新打开！
    String CLOSE_THE_PRIOR_PERIOD_FIRST = "6026003"; //请先关闭前一个期间，否则不能关闭当前期间！
    String YEAR_FROM_SHOULD_BE_LESS_THEN_YEAR_TO = "6026004"; //年度从的时间应该小于或等于年度到！
    String ACCOUNTING_ENTITY_DOES_NOT_EXIST = "6026005"; //会计期实体不存在！
    String ACCOUNTING_RULES_DO_NOT_EXIST = "6026006"; //会计期规则不存在!
    String FILLIN_YEAR_REPEAT = "6026007"; //包含已经录入的年度，请重新填写年份！
    String PERIODSETCODE_IS_EMPTY = "6026008"; //会计期代码不能为空
    String Year_IS_EMPTY = "6026009"; //年度不能为空
    String YEAR_EXCEEDS_THE_PREDEFINED_TIME_LIMIT_OF_TIME_STAMP = "6026011"; //年度超出时间戳定义年限!

    String OBJECT_NOT_FOUND = "4001";   //对象没找到
    String REQUEST_FREQUENCY_TOO_FAST = "9960";   //请求频率过快!

    //科目表明细
    String ACCOUNTS_ID_NOT_NULL = "6033001";  //科目表明细ID应为空
    String ACCOUNTS_ID_NULL = "6033002";  //科目表ID不能为空
    String ACCOUNTS_CODE_NULL = "6033003";  //科目代码不能为空
    String ACCOUNTS_NAME_NULL = "6033004";  //科目名称不能为空
    String ACCOUNTS_TENANT_ID_NULL = "6033005";  //租户ID不能为空
    String ACCOUNTS_CODE_EXISTS = "6033006";  //当前科目代码已存在
    String ACCOUNTS_NOT_EXISTS = "6033007";  //当前科目不存在
    String ACCOUNTS_NAME_EXISTS = "6033008";  //当前科目名称已存在
    String ACCOUNTS_HAS_SUB_ACCONUT = "6033009";  //不能改变汇总标志,当前科目下存在子科目

    //科目表设置
    String ACCOUNTSET_EXISTS = "6019001";  //当前科目表已存在
    String ACCOUNTSET_NOT_EXISTS = "6019002";  //当前科目表不存在
    String ACCOUNTSET_CODE_EXISTS = "6019003";  //当前科目表代码已存在
    String ACCOUNTSET_CODE_NULL = "6019004";  //科目表代码不能为空
    String ACCOUNTSET_DESC_NULL = "6019005";  //科目表描述不能为空
    String ACCOUNTSET_ID_NOT_NULL = "6019006";  //当前科目表ID应该为空值
    String ACCOUNTSET_ID_NULL = "6019007";  //当前科目表ID不能为空值
    String ACCOUNTSET_TENANT_ID_NULL = "6019008";  //当前科目表租户ID不能为空

    //科目表层级
    String ACCOUNTSHIERARCHY_ID_NOT_NULL = "6034001";  //科目层级ID应为空
    String ACCOUNTSHIERARCHY_PARENT_ID_NULL = "6034002";  //父级科目ID不能为空
    String ACCOUNTSHIERARCHY_SUB_ID_NULL = "6034003";  //子级科目ID不能空
    String ACCOUNTSHIERARCHY_TENANT_ID_NULL = "6034004";  //租户ID不能空
    String ACCOUNTSHIERARCHY_HAS_SAME_SUB_ACCOUNT = "6034005";  //当前父级科目下已存在相同子科目
    String ACCOUNTSHIERARCHY_NOT_EXISTS = "6034006";  //科目层级不存在


    //维度
    String SYS_FIELD_IS_NULL = "SYS_FIELD_IS_NULL";  //必输字段不允许为空！
    String DIMENSION_CODE_REPEAT = "DIMENSION_CODE_REPEAT";  //账套下维度代码不允许重复！
    String DIMENSION_NAME_REPEAT = "DIMENSION_NAME_REPEAT";  //账套下维度名称不允许重复！
    String DIMENSION_SEQUENCE_REPEAT = "DIMENSION_SEQUENCE_REPEAT";  //账套下维度序号不允许重复！
    String DIMENSION_SEQUENCE_MUST_BETWEEN_1_AND_20 = "DIMENSION_SEQUENCE_MUST_BETWEEN_1_AND_20";  //维度序号必须在1到20之间！
    String DIMENSION_QUANTITY_MORE_THEN_20 = "DIMENSION_QUANTITY_MORE_THEN_20";  //账套下维度数量不能超过20！
    String DIMENSION_ASSIGN_COMPANY_CODE_REPEAT = "DIMENSION_ASSIGN_COMPANY_CODE_REPEAT";  //该公司已经分配，不允许重新分配！
    String DIMENSION_ITEM_CODE_REPEAT = "DIMENSION_ITEM_CODE_REPEAT";  //同一维度下维值代码不允许重复！
    String DIMENSION_ITEM_GROUP_CODE_REPEAT = "DIMENSION_ITEM_GROUP_CODE_REPEAT";  //同一维度下维值组代码不允许重复！
    String DIMENSION_ITEM_GROUP_NAME_REPEAT = "DIMENSION_ITEM_GROUP_NAME_REPEAT";  //同一维度下维值组名称不允许重复！
    String DIMENSION_NOT_EXIST = "DIMENSION_NOT_EXIST"; //维度不存在！
    String DIMENSION_ITEM_COMPANY_NOT_EXIST = "DIMENSION_ITEM_COMPANY_NOT_EXIST"; //维值关联公司不存在！
    String DIMENSION_SETOFBOOKS_NOT_EXIST = "DIMENSION_SETOFBOOKS_NOT_EXIST"; //该账套不存在！
    String DIMENSION_ITEM_NOT_EXIST = "DIMENSION_ITEM_NOT_EXIST"; //维值不存在！

   String SETOFBOOKS_NOT_EXIST = "SETOFBOOKS_NOT_EXIST"; //当前账套不存在

    //数据权限
    String AUTH_DATA_AUTHORITY_CITED = "AUTH_DATA_AUTHORITY_CITED";        //该数据权限已被引用，不可删除！
    String AUTH_DATA_AUTHORITY_RULE_EXISTS = "AUTH_DATA_AUTHORITY_RULE_EXISTS";  //同一权限下，规则名称不能重复！
    String AUTH_DATA_AUTHORITY_RULE_DETAIL_VALUE_NONE = "AUTH_DATA_AUTHORITY_RULE_DETAIL_VALUE_NONE";   //数据权限为手工选择时，请至少选择一条数据！
    String AUTH_DATA_AUTHORITY_RULE_DETAIL_EXISTS = "AUTH_DATA_AUTHORITY_RULE_DETAIL_EXISTS";   //数据权限规则数据类型已存在，请勿重复保存！
    String AUTH_DATA_AUTHORITY_EXISTS = "AUTH_DATA_AUTHORITY_EXISTS";   //数据权限已存在，请勿重复保存！

    //数据权限参数配置
    String AUTH_DATA_AUTH_TABLE_PROPERTY_DATA_TYPE_EXISTS = "AUTH_DATA_AUTH_TABLE_PROPERTY_DATA_TYPE_EXISTS";//此参数类型在该表名下已经存在!
    String AUTH_DATA_AUTH_TABLE_PROPERTY_COLUMN_NAME_EXISTS = "AUTH_DATA_AUTH_TABLE_PROPERTY_COLUMN_NAME_EXISTS";//此参数名称在该表名下已经存在!


    //公告信息
    String Carousel_6041001 = "6041001";
    String Carousel_6041003 = "6041003";
    String Carousel_6041004 = "6041004"; //carouselOIDs or companyIDs,RequestParam can't be null

    //责任中心
    String RESPONSIBILITY_CENTER_CONFIGURE_REPEAT="RESPONSIBILITY_CENTER_CONFIGURE_REPEAT"; //此账套配置项重复，请修改配置
    String RESPONSIBILITY_CENTER_NOT_EXIST="RESPONSIBILITY_CENTER_NOT_EXIST"; //"当前责任中心不存在"
    String RESPONSIBILITY_CENTER_GROUP_NOT_EXIST="RESPONSIBILITY_CENTER_GROUP_NOT_EXIST";//"当前责任中心组不存在"
    String RESPONSIBILITY_CENTER_DEPARTMENTSOB_NOT_EXIST="RESPONSIBILITY_CENTER_DEPARTMENTSOB_NOT_EXIST"; //当前部门责任中心不存在
    String RESPONSIBILITY_CENTER_COMPANY_NOT_EXIST="RESPONSIBILITY_CENTER_COMPANY_NOT_EXIST";//责任中心关联公司不存在!
    String RESPONSIBILITY_CENTER_CODE_REPEAT="RESPONSIBILITY_CENTER_CODE_REPEAT";//一个账套下责任中心代码不可重复
    String RESPONSIBILITY_CENTER_GROUP_CODE_REPEAT="RESPONSIBILITY_CENTER_GROUP_CODE_REPEAT";//一个账套下责任中心组代码不可重复

    //参数定义
    String PARAMETER_VALUES_NOT_EXIST="PARAMETER_VALUES_NOT_EXIST";//当前参数值不存在!
    String PARAMETER_SETTING_NOT_EXIST="PARAMETER_SETTING_NOT_EXIST";//当前参数明细不存在!
    String PARAMETER_NOT_EXIST="PARAMETER_NOT_EXIST";//当前参数不存在!

    //地点级别
    String LOCATION_LEVEL_CODE_REPEAT = "LOCATION_LEVEL_CODE_REPEAT";//账套下地点级别重复
    String LOCATION_LEVEL_NOT_EXIST = "LOCATION_LEVEL_NOT_EXIST";//地点级别不存在
}
