image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.5.0

variables:
    MAVEN_OPTS: -Dmaven.repo.local=/cache/local/repo
stages:
- build
- dev-release
cache:
    key: one-key-to-rull-them-all
    paths:
    - /cache/local/repo
build:
    stage: build
    script: "mvn -U clean package"
    only:
    - tags
    - master
    - development
    - /^release-.*$/

dev-release:
    stage: dev-release
    only:
    - tags
    - development
    - /^release-.*$/
    when: manual
    script:
    - "mvn compile jib:build -Dci_pipeline_id=$CI_PIPELINE_ID"



