package com.hand.hcf.app.prepayment.enums;

public enum AttachmentType {
    COMPANY_LOGO, FEEDBACK_IMAGES, INVOICE_IMAGES, IMAGE_INVOICE_IMAGES, HEAD_PORTRAIT, CARROUSEL_IMAGES, PDF, REPAYMENT_IMAGES, EXPENSE_ICON,PREPAYMENT
}