spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  liquibase:
    change-log: classpath:db/liquibase/master.xml
  application:
    name: auth
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

