spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://106.15.120.125:21906/artemis?useUnicode=true&characterEncoding=utf8
    name:
    username: artemis
    password: MTIzNDU2TXMz
  redis:
    host: redis
    port: 6379
    password:

auth:
  cache:
    expire-time: 30

logging:
  config: classpath:logback/logback-stage.xml

dingtalk:
    server:
        getDingTalkUserInfoURL: http://dingtalkstage.huilianyi.com/dingtalk/common/get/user/info

single-sign:
  server:
    host: http://sso-service:11059
    access-token-uri: http://auth-service:9999/oauth/token
    client-id: implement-integration
    client-secret: K2QzPPz3fqQNEnsbwupD1b1IDPPg0RfkdWalXysL7wd

wechat:
    wechatUrl: http://wechat-service:11001/wechat-service/wechat/

haima:
    server:
        userMapping: http://haima-service:9090/haima/api/user/mapping
        userInfo: http://haima-service:9090/haima/api/user/userInfo

app-center:
  authentication:
    download-url: http://downloads.huilianyi.com/app/sit
    client-id: ArtemisWeb

trialService:
    api:
        host: http://apiuat.huilianyi.com
        get_trialUser: ${trialService.api.host}/trial/public/getTrialUser
        bind_wechat_user: ${trialService.api.host}/trial/public/bind