server:
  port: 9082
spring:
  dbType: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.159.108.80:3306/artemis_uat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    name:
    username: standarddb #artemis
    password: mysql112358 #MTIzNDU2TXMz
  redis:
    host: redis
    port: 6379
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    ip-address: 115.159.108.80
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    registryFetchIntervalSeconds: 10
mybatis:
  mapper-locations: com/helioscloud/atlantis/persistence/*Mapper.xml
  type-aliases-package: com.helioscloud.atlantis.domain
  type-handlers-package: com.helioscloud.atlantis.persistence.typehandler
auth:
  cache:
    expire-time: 30
logging:
  config: classpath:logback/logback-dev.xml

single-sign:
  server:
    host: http://sso-service:11059
    access-token-uri: http://auth-service:9999/auth/oauth/token
    client-id: implement-integration
    client-secret: K2QzPPz3fqQNEnsbwupD1b1IDPPg0RfkdWalXysL7wd

wechat:
    wechatUrl: http://wechat-service:11001/wechat-service/wechat/

haima:
    server:
        userMapping: http://haima-service:9090/haima/api/user/mapping
        userInfo: http://haima-service:9090/haima/api/user/userInfo


app-center:
  authentication:
    download-url: http://downloads.huilianyi.com/app/sit
    client-id: ArtemisWeb

trialService:
    api:
        host: http://apiuat.huilianyi.com
        get_trialUser: ${trialService.api.host}/trial/public/getTrialUser
        bind_wechat_user: ${trialService.api.host}/trial/public/bind
elasticsearch:
  cluster-name : docker-cluster
  host: 115.159.108.80
  tcp-port: 9300
  user: elastic
  password: changeme
  enable: true
feign:
  httpclient:
    enabled: false
  okhttp:
    enable: true
debug: true