server:
  port: 9082
spring:
  dbType: mysql
  datasource:
    url: jdbc:mysql://30.50.48.85:3306/ali_dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ali_dev
    password: ali_dev
    maximum-pool-size: 10
    pool-name: HikariPool
    type: com.zaxxer.hikari.HikariDataSource
  cache:
    cache-names: HCF_TOKEN
    type: caffeine

mybatis-plus:
  mapper-locations: com/hand/hcf/app/base/persistence/*Mapper.xml
  type-aliases-package: com.hand.hcf.app.**.domain
  type-handlers-package: com.hand.hcf.app.core.persistence.typehandler
  enable-performance-interceptor: true
  type-enums-package: com.hand.hcf.app.**.enums

security:
  oauth2:
    client:
      access-token-uri: http://localhost:9082/oauth/token
      client-authentication-scheme: form
      client-id: implement-integration
      client-secret: K2QzPPz3fqQNEnsbwupD1b1IDPPg0RfkdWalXysL7wd
      grant-type: client_credentials
    resource:
      user-info-uri: http://localhost:9082/api/check_token

logging:
  config: classpath:logback/logback-prod.xml

single-sign:
  server:
    host: http://sso-service:11059
    access-token-uri: http://auth-service:9999/auth/oauth/token
    client-id: implement-integration
    client-secret: K2QzPPz3fqQNEnsbwupD1b1IDPPg0RfkdWalXysL7wd

wechat:
  wechatUrl: http://wechat-service:11001/wechat-service/wechat/

haima:
  server:
    userMapping: http://haima-service:9090/haima/api/user/mapping
    userInfo: http://haima-service:9090/haima/api/user/userInfo

app-center:
  authentication:
    download-url: http://downloads.huilianyi.com/app/sit
    client-id: ArtemisWeb

trialService:
  api:
    host: http://apiuat.huilianyi.com
    get_trialUser: ${trialService.api.host}/trial/public/getTrialUser
    bind_wechat_user: ${trialService.api.host}/trial/public/bind

management:
  health:
    rabbit:
      enabled: false

async:
  enable: true
  max-pool-size: 250
  queue-capacity: 8
  core-pool-size: 8
  keep-alive-seconds: 30

hcf:
   storage:
     oss:
       endpoint: oss-cn-hangzhou.aliyuncs.com
       Client:
         id: LTAILXuGflnRebM1
         secret: La2LjuhgAqtJttgGmwMrRwj7tfsTQE
       Bucket:
         name: hand-ant-reimburse1
       filehost: gfbrmp
     mode: OSS
