server:
  port: 9082
spring:
  dbType: oracle
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@47.101.143.73:1521/hcfuatp1
    username: hcf_organization
    password: handhand
  #  dbType: oracle
  #  datasource:
        #driver-class-name: com.mysql.jdbc.Driver
        #url: jdbc:mysql://localhost:3306/artemis_multi_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
        #url: jdbc:mysql://115.159.108.80:3306/artemis_uat?useUnicode=true&characterEncoding=utf-8&useSSL=false #jdbc:mysql://106.15.120.125:21906/artemis_dev02?useUnicode=true&characterEncoding=utf8
        #username: root
        #password: handhand
   #     type: com.alibaba.druid.pool.DruidDataSource
   #     url: jdbc:oracle:thin:@115.159.108.80:1521:RJFIN
   #     username: standard_artemis
   #     password: handhand
    maximum-pool-size: 10
    pool-name: HikariPool
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: localhost
    port: 6379
  cloud:
    bus:
      enabled: false
  cache:
    cache-names: HCF_TOKEN
    type: caffeine

j2cache:
  open-spring-cache: true
  allow-null-values: true
  cache-clean-mode: passive
  serialization: com.hand.hcf.core.j2cache.support.util.KryoSerializer
  sync_ttl_to_redis: true
  broadcast:
    provider: com.hand.hcf.core.j2cache.support.redis.SpringRedisPubSubPolicy
  L1:
    provider: caffeine
    region:
      HCF_TOKEN: 3000,24h
      default: 3000,24h
  L2:
    provider: com.hand.hcf.core.j2cache.support.redis.SpringRedisProvider
    database: 0
    channel: j2cache
    storage: generic

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8300/eureka}
    registryFetchIntervalSeconds: 10
    enabled: false
mybatis:
  mapper-locations: com/hand/hcf/app/base/persistence/*Mapper.xml
  type-aliases-package: com.hand.hcf.app.base.domain
  type-handlers-package: com.hand.hcf.core.persistence.typehandler
  enable-performance-interceptor: true

#
#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:9082/oauth/token
#      client-authentication-scheme: form
#      client-id: implement-integration
#      client-secret: K2QzPPz3fqQNEnsbwupD1b1IDPPg0RfkdWalXysL7wd
#      grant-type: client_credentials
#    resource:
#      user-info-uri: http://localhost:9082/api/check_token

logging:
  config: classpath:logback/logback-dev.xml

single-sign:
  server:
    host: http://sso-service:11059
    access-token-uri: http://auth-service:9999/auth/oauth/token
    client-id: implement-integration
    client-secret: K2QzPPz3fqQNEnsbwupD1b1IDPPg0RfkdWalXysL7wd

wechat:
    wechatUrl: http://wechat-service:11001/wechat-service/wechat/

haima:
    server:
        userMapping: http://haima-service:9090/haima/api/user/mapping
        userInfo: http://haima-service:9090/haima/api/user/userInfo


app-center:
  authentication:
    download-url: http://downloads.huilianyi.com/app/sit
    client-id: ArtemisWeb

trialService:
    api:
        host: http://apiuat.huilianyi.com
        get_trialUser: ${trialService.api.host}/trial/public/getTrialUser
        bind_wechat_user: ${trialService.api.host}/trial/public/bind

hcf:
  application:
    base:
      url: http://localhost:9083
feign:
  httpclient:
    enabled: false
  okhttp:
    enable: true

management:
  health:
    rabbit:
      enabled: false
