server:
  port: 9082
spring:
  liquibase:
      change-log: classpath:db/liquibase/master.xml
  dbType: oracle
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbcUrl: jdbc:oracle:thin:@172.17.0.4:1521:RJFIN
    name:
    username: standard_artemis #artemis
    password: handhand #MTIzNDU2TXMz
    type: com.zaxxer.hikari.HikariDataSource
  #  dbType: oracle
  #  datasource:
        #driver-class-name: com.mysql.jdbc.Driver
        #url: jdbc:mysql://localhost:3306/artemis_multi_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
        #url: jdbc:mysql://115.159.108.80:3306/artemis_uat?useUnicode=true&characterEncoding=utf-8&useSSL=false #jdbc:mysql://106.15.120.125:21906/artemis_dev02?useUnicode=true&characterEncoding=utf8
        #username: root
        #password: handhand
   #     type: com.alibaba.druid.pool.DruidDataSource
   #     url: jdbc:oracle:thin:@115.159.108.80:1521:RJFIN
   #     username: standard_artemis
   #     password: handhand
  redis:
    host: redis
    port: 6379
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    ip-address: 192.168.11.252
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://115.159.108.80:9070}
    registryFetchIntervalSeconds: 10
    enabled: false
mybatis:
  mapper-locations: com/helioscloud/atlantis/persistence/*Mapper.xml
  type-aliases-package: com.helioscloud.atlantis.domain
  type-handlers-package: com.helioscloud.atlantis.persistence.typehandler
  enable-performance-interceptor: true
auth:
  cache:
    expire-time: 30
logging:
  config: classpath:logback/logback-dev.xml

single-sign:
  server:
    host: http://sso-service:11059
    access-token-uri: http://auth-service:9999/auth/oauth/token
    client-id: implement-integration
    client-secret: K2QzPPz3fqQNEnsbwupD1b1IDPPg0RfkdWalXysL7wd

wechat:
    wechatUrl: http://wechat-service:11001/wechat-service/wechat/

haima:
    server:
        userMapping: http://haima-service:9090/haima/api/user/mapping
        userInfo: http://haima-service:9090/haima/api/user/userInfo


app-center:
  authentication:
    download-url: http://downloads.huilianyi.com/app/sit
    client-id: ArtemisWeb

trialService:
    api:
        host: http://apiuat.huilianyi.com
        get_trialUser: ${trialService.api.host}/trial/public/getTrialUser
        bind_wechat_user: ${trialService.api.host}/trial/public/bind
elasticsearch:
  cluster-name : docker-cluster
  host: 115.159.108.80
  tcp-port: 9300
  user: elastic
  password: changeme
  enable: true
feign:
  httpclient:
    enabled: false
  okhttp:
    enable: true