package com.hand.hcf.app.expense.common.utils;

public interface RespCode {
    // 数据库找不到对象
    String SYS_OBJECT_IS_EMPTY = "SYS_OBJECT_IS_EMPTY";
    //调用支付模块服务异常！
    String SYS_PAYMENT_SERVICE_EXCEPTION = "SYS_PAYMENT_SERVICE_EXCEPTION";
    //
    String SYS_CHECK_NULL = "SYS_CHECK_NULL";
    // ID 不允许为空
    String SYS_ID_IS_NULL = "SYS_ID_IS_NULL";
    String SYS_ID_IS_NOT_NULL = "SYS_ID_IS_NOT_NULL";
    // 数据已存在
    String SYS_DATA_ALREADY_EXISTS = "SYS_DATA_ALREADY_EXISTS";
    String SYS_DATA_NOT_EXISTS = "SYS_DATA_NOT_EXISTS";  //数据不存在
    // 必输字段不允许为空
    String SYS_FIELD_IS_NULL = "SYS_FIELD_IS_NULL";
    String SYS_VERSION_IS_ERROR = "SYS_VERSION_IS_ERROR";
    String SYS_DATA_FORMAT_ERROR = "SYS_DATA_FORMAT_ERROR";//数据格式错误
    /**
     * 必输字段不能为空！
     */
    String SYS_REQUIRED_FIELD_NONE = "SYS_REQUIRED_FIELD_NONE";
    // 关联申请类型不允许为空
    String EXPENSE_ASSOICATE_TYPE_NOT_EXISTS = "EXPENSE_ASSOICATE_TYPE_NOT_EXISTS";
    // 适用人员不允许为空
    String EXPENSE_ASSOICATE_USER_NOT_EXISTS1 = "EXPENSE_ASSOICATE_USER_NOT_EXISTS1";
    // 费用申请单类型代码已经存在，不允许重复
    String EXPENSE_APPLICATION_TYPE_CODE_EXISTS = "EXPENSE_APPLICATION_TYPE_CODE_EXISTS";
    // 请选择适用公司
    String EXPENSE_ASSIGN_COMPANY_IS_NULL = "EXPENSE_ASSIGN_COMPANY_IS_NULL";
    // 请选择适用人员
    String EXPENSE_ASSIGN_USER_IS_NULL = "EXPENSE_ASSIGN_USER_IS_NULL";
    // 类型不同，不允许更新
    String EXPENSE_TYPE_ERROR = "EXPENSE_TYPE_ERROR";
    /**
     * 申请类型代码已存在
     */
    String EXPENSE_TYPE_APPLICATION_CODE_IS_EXISTS = "EXPENSE_TYPE_APPLICATION_CODE_IS_EXISTS";
    /**
     * 费用类型代码已存在
     */
    String EXPENSE_TYPE_EXPENSE_CODE_IS_EXISTS = "EXPENSE_TYPE_EXPENSE_CODE_IS_EXISTS";
    // 请选择数量的格式
    String EXPENSE_TYPE_PRICE_UNIT_IS_NULL = "EXPENSE_TYPE_PRICE_UNIT_IS_NULL";
    // 选中的值列表没有相关的值
    String EXPENSE_TYPE_SYS_CODE_IS_NULL = "EXPENSE_TYPE_SYS_CODE_IS_NULL";
    String EXPENSE_APPLICATION_DIMENSION_IS_NULL = "EXPENSE_APPLICATION_DIMENSION_IS_NULL";

    String EXPENSE_APPLICATION_DIMENSION_DUPLICATE = "EXPENSE_APPLICATION_DIMENSION_DUPLICATE";
    // 用户所属账套的本位币为空
    String EXPENSE_APPLICATION_CURRENCY_CODE_IS_NULL = "EXPENSE_APPLICATION_CURRENCY_CODE_IS_NULL";
    // 关联的申请类型必须存在
    String EXPENSE_TYPE_NOT_FOUND_SOURCE_TYPE = "EXPENSE_TYPE_NOT_FOUND_SOURCE_TYPE";
    // 费用申请单类型不允许为空
    String EXPENSE_APPLICATION_TYPE_IS_NUTT = "EXPENSE_APPLICATION_TYPE_IS_NUTT";
    // 关联的合同必须不为空
    String EXPENSE_ASSOICATE_CONTRACT_IS_NULL = "EXPENSE_ASSOICATE_CONTRACT_IS_NULL";
    // 关联的维度不允许为空
    String EXPENSE_DIMENSIONS_IS_NULL = "EXPENSE_DIMENSIONS_IS_NULL";
    // 维度的默认值不允许为空
    String EXPENSE_DIMENSION_DEFAULT_VALUE_IS_NULL = "EXPENSE_DIMENSION_DEFAULT_VALUE_IS_NULL";
    // 设置维度值时发生异常
    String EXPENSE_SET_DIMENSION_ID_ERROR = "EXPENSE_SET_DIMENSION_ID_ERROR";
    // 费用申请单行金额不允许为空！
    String EXPENSE_APPLICATION_LINE_AMOUNT_IS_NULL = "EXPENSE_APPLICATION_LINE_AMOUNT_IS_NULL";
    // {0}申请单存在未结束流程的关联报账单{1}，请结束流程或退回后再关闭！
    String EXPENSE_APPLICATION_HEADER_CLOSE_CHECK_ERROR = "EXPENSE_APPLICATION_HEADER_CLOSE_CHECK_ERROR";
    // 费用申请单行单价和数量不允许为空！
    String EXPENSE_APPLICATION_LINE_PRICE_IS_NULL = "EXPENSE_APPLICATION_LINE_PRICE_IS_NULL";
    // 申请单单据头不存在
    String EXPENSE_APPLICATION_HEADER_ID_IS_NULL = "EXPENSE_APPLICATION_HEADER_ID_IS_NULL";
    // 单据状态不允许进行此处操作，请检查单据状态！
    String EXPENSE_APPLICATION_STATUS_ERROR = "EXPENSE_APPLICATION_STATUS_ERROR";
    // 为获取到会计期间
    String EXPENSE_PERIODS_ERROR = "EXPENSE_PERIODS_ERROR";
    // 调用预算模块发生未知异常
    String EXPENSE_EXPENSE_PERIODS_ERROR = "EXPENSE_EXPENSE_PERIODS_ERROR";
    // 申请单行信息为空，不允许提交！
    String EXPENSE_APPLICATION_LINE_IS_NULL = "EXPENSE_APPLICATION_LINE_IS_NULL";
    // 申请单提交发生异常！
    String EXPENSE_APPLICATION_SUBMIT_ERROR = "EXPENSE_APPLICATION_SUBMIT_ERROR";
    // 预算校验失败
    String EXPENSE_BUDGET_CHECK_ERROR = "EXPENSE_BUDGET_CHECK_ERROR";
    // 释放预算时发生未知异常
    String EXPENSE_ROLLBACK_BUDGET_ERROR = "EXPENSE_ROLLBACK_BUDGET_ERROR";

    String EXPENSE_CATEGORY_EXISTS_TYPE = "EXPENSE_CATEGORY_EXISTS_TYPE";
    // 收款方信息不完整
    String EXPENSE_PUBLIC_REPORT_ACCOUNT_INFO_IS_NOT_COMPLETE = "EXPENSE_PUBLIC_REPORT_ACCOUNT_INFO_IS_NOT_COMPLETE";
    String EXPENSE_PUBLIC_REPORT_CONTRACT_IS_NULL = "EXPENSE_PUBLIC_REPORT_CONTRACT_IS_NULL";//合同信息不能为空
    String EXPENSE_FORM_ASSIGN_INFO_IS_NULL = "EXPENSE_FORM_ASSIGN_INFO_IS_NULL";//请维护报账单表单信息
    String EXPENSE_DEPARTMENT_IS_NULL = "EXPENSE_DEPARTMENT_IS_NULL"; // 部门不存在或者已被删除
    String EXPENSE_AGENT_PERMISSION_ERROR = "EXPENSE_AGENT_PERMISSION_ERROR";//代理人权限错误

    String EXPENSE_ADJUST_LINE_IMPORT_INDEX_ERROR = "EXPENSE_ADJUST_LINE_IMPORT_INDEX_ERROR"; // 导入的序号不允许为空或者重复！
    String EXPENSE_ADJUST_TYPE_IS_NOT_EXISTS = "EXPENSE_ADJUST_TYPE_IS_NOT_EXISTS"; // 费用调整单单据类型不存在
    String EXPENSE_ADJUST_TYPE_CODE_IS_EXISTS = "EXPENSE_ADJUST_TYPE_CODE_IS_EXISTS"; // 费用调整单单据类型代码已经存在
    String EXPENSE_ADJUST_TYPE_APPLY_DOCUMENT = "EXPENSE_ADJUST_TYPE_APPLY_DOCUMENT"; // 该类型已应用于单据，不允许删除！
    String EXPENSE_ADJUST_TYPE_ASSIGN_COMPANY_IS_EXISTS = "EXPENSE_ADJUST_TYPE_ASSIGN_COMPANY_IS_EXISTS"; // 该公司已经分配，不允许重新分配！
    String EXPENSE_ADJUST_HEADER_IS_NOT_EXISTS = "EXPENSE_ADJUST_HEADER_IS_NOT_EXISTS"; // 费用调整单单据头信息不存在！
    String EXPENSE_ADJUST_LINE_AMOUNT_IS_ZERO = "EXPENSE_ADJUST_LINE_AMOUNT_IS_ZERO"; // 费用补录金额不允许为零！
    String EXPENSE_ADJUST_LINE_COMPANY_IS_NULL= "EXPENSE_ADJUST_LINE_COMPANY_IS_NULL"; // 公司不允许为空！
    String EXPENSE_ADJUST_LINE_UNIT_IS_NULL= "EXPENSE_ADJUST_LINE_UNIT_IS_NULL"; // 部门不允许为空！

    String EXPENSE_ADJUST_LINE_RESPONSIBILITY_CENTER_IS_NULL = "EXPENSE_ADJUST_LINE_RESPONSIBILITY_CENTER_IS_NULL";//责任中心不允许为空！

    String EXPENSE_ADJUST_LINE_EXPENSE_TYPE_IS_NULL = "EXPENSE_ADJUST_LINE_EXPENSE_TYPE_IS_NULL"; // 费用类型不允许为空！
    String EXPENSE_ADJUST_LINE_IS_NULL = "EXPENSE_ADJUST_LINE_IS_NULL"; // 费用分摊数据不存在！

    //费用预提单
    String EXPENSE_ACCRUAL_TYPE_IS_NOT_EXISTS = "EXPENSE_ACCRUAL_TYPE_IS_NOT_EXISTS"; // 费用预提单类型不存在
    String EXPENSE_ACCRUAL_TYPE_CODE_IS_EXISTS = "EXPENSE_ACCRUAL_TYPE_CODE_IS_EXISTS"; // 当前帐套下费用预提单代码已存在

//    发票类型定义
    String INVOICE_TYPE_CODE_REPEAT = "INVOICE_TYPE_CODE_REPEAT"; //同一租户下发票类型代码不可重复
    String INVOICE_TYPE_NOT_EXIST ="INVOICE_TYPE_NOT_EXIST"; //当前发票类型定义不存在
    String INVOICE_TYPE_HEAD_COLUMN_NOT_EXIST ="INVOICE_TYPE_HEAD_COLUMN_NOT_EXIST"; //当前发票类型头不存在
    String INVOICE_TYPE_LINE_COLUMN_NOT_EXIST ="INVOICE_TYPE_LINE_COLUMN_NOT_EXIST"; //当前发票类型行不存在
    String INVOICR_TYPE_NUMBER_IS_INTEGER="INVOICR_TYPE_NUMBER_IS_INTEGER";//发票代码位数/发票号码位数须为正整数


    /**
     * 发票费用映射规则表
     */
    String INVOICE_EXPENSE_TYPE_RULES_ID_IS_NULL = "INVOICE_EXPENSE_TYPE_RULES_ID_IS_NULL";//发票费用映射规则表id不为空！

    //发票头
    String INVOICE_HEAD_ID_IS_NOT_NULL = "INVOICE_HEAD_ID_IS_NOT_NULL";//发票头id不为空！
    String INVOICE_HEADER_IS_NULL = "INVOICE_HEADER_IS_NULL"; //发票头信息不存在！
    String INVOICE_CERTIFICATION_STATUS_ERROR = "INVOICE_CERTIFICATION_STATUS_ERROR";//发票状态不允许进行此处操作，请检查发票状态！
    String INVOICE_HEAD_ID_IS_NULL = "INVOICE_HEAD_ID_IS_NULL";//发票头id为空！
    String INVOICE_HEAD_TENANT_ID_IS_NULL = "INVOICE_HEAD_TENANT_ID_IS_NULL";//发票头租户id为空！
    String INVOICE_HEAD_SET_OF_BOOKS_ID_IS_NULL = "INVOICE_HEAD_SET_OF_BOOKS_ID_IS_NULL";//发票头账套id为空！
    String INVOICE_HEAD_INVOICE_NO_IS_NULL = "INVOICE_HEAD_INVOICE_NO_IS_NULL";//发票头发票号码为空！
    String INVOICE_HEAD_INVOICE_CODE_IS_NULL = "INVOICE_HEAD_INVOICE_CODE_IS_NULL";//发票头发票代码为空！
    String INVOICE_HEAD_TOTAL_AMOUNT_IS_NULL = "INVOICE_HEAD_TOTAL_AMOUNT_IS_NULL";//发票头价税合计为空！
    String INVOICE_HEAD_CURRENCY_CODE_IS_NULL = "INVOICE_HEAD_CURRENCY_CODE_IS_NULL";//发票头币种为空！
    String INVOICE_HEAD_EXCHANGE_RATE_IS_NULL = "INVOICE_HEAD_EXCHANGE_RATE_IS_NULL";//发票头汇率为空！
    String INVOICE_HEAD_CANCEL_FLAG_IS_NULL = "INVOICE_HEAD_CANCEL_FLAG_IS_NULL";//发票头作废标志为空！
    String INVOICE_HEAD_RED_INVOICE_FLAG_IS_NULL = "INVOICE_HEAD_RED_INVOICE_FLAG_IS_NULL";//发票头红票标志为空！
    String INVOICE_HEAD_CREATED_METHOD_IS_NULL = "INVOICE_HEAD_CREATED_METHOD_IS_NULL";//发票头创建方式为空！
    String INVOICE_HEAD_EXIST_PLEASE_IMPORT_FROM_THE_TICKET_FOLDER = "INVOICE_HEAD_EXIST_PLEASE_IMPORT_FROM_THE_TICKET_FOLDER";//此发票已经存在，请从票夹导入！
    String INVOICE_HEAD_REPEAT_WITH_OTHERS_PLEASE_REPLACE_THE_INVOICE = "INVOICE_HEAD_REPEAT_WITH_OTHERS_PLEASE_REPLACE_THE_INVOICE";//此发票与员工姓名-工号录入的发票重复，请更换发票！

    //发票行
    String INVOICE_LINE_IS_EMPTY = "INVOICE_LINE_IS_EMPTY";//发票行为空！
    String INVOICE_LINE_ID_IS_NOT_NULL = "INVOICE_LINE_ID_IS_NOT_NULL";//发票行id不为空！
    String INVOICE_LINE_ID_IS_NULL = "INVOICE_LINE_ID_IS_NULL";//发票行id为空！
    String INVOICE_LINE_TENANT_ID_IS_NULL = "INVOICE_LINE_TENANT_ID_IS_NULL";//发票行租户id为空！
    String INVOICE_LINE_SET_OF_BOOKS_ID_IS_NULL = "INVOICE_LINE_SET_OF_BOOKS_ID_IS_NULL";//发票行账套id为空！
    String INVOICE_LINE_INVOICE_HEAD_ID_IS_NULL = "INVOICE_LINE_INVOICE_HEAD_ID_IS_NULL";//发票行中发票头id为空！
    String INVOICE_LINE_INVOICE_LINE_NUM_IS_NULL = "INVOICE_LINE_INVOICE_LINE_NUM_IS_NULL";//发票行中发票行序号为空！
    String INVOICE_LINE_DETAIL_AMOUNT_IS_NULL = "INVOICE_LINE_DETAIL_AMOUNT_IS_NULL";//发票行金额为空！
    String INVOICE_LINE_TAX_RATE_IS_NULL = "INVOICE_LINE_TAX_RATE_IS_NULL";//发票行税率为空！
    String INVOICE_LINE_TAX_AMOUNT_IS_NULL = "INVOICE_LINE_TAX_AMOUNT_IS_NULL";//发票行税额为空！
    String INVOICE_LINE_TAX_AMOUNT_NO_MORE_THAN_DETAIL_AMOUNT_MULTIPLIED_BY_TAX_RATE = "INVOICE_LINE_TAX_AMOUNT_NO_MORE_THAN_DETAIL_AMOUNT_MULTIPLIED_BY_TAX_RATE";//发票行税额不可以大于金额*税率，请检查并修改！
    String INVOICE_LINE_DETAIL_AMOUNT_SUM_NO_MORE_THAN_HEAD_INVOICE_AMOUNT_SUM = "INVOICE_LINE_DETAIL_AMOUNT_SUM_NO_MORE_THAN_HEAD_INVOICE_AMOUNT_SUM";//发票行金额之和不可大于整张发票金额！
    String INVOICE_LINE_TAX_AMOUNT_SUM_NO_MORE_THAN_HEAD_TAX_TOTAL_AMOUNT_SUM = "INVOICE_LINE_TAX_AMOUNT_SUM_NO_MORE_THAN_HEAD_TAX_TOTAL_AMOUNT_SUM";//发票行金额之和不可大于整张发票金额！
    String INVOICE_LINE_IS_ALLOTED = "INVOICE_LINE_IS_ALLOTED";//发票行已经被分配

    //费用政策
    String EXPENSE_PLOICY_PRIORITY_REPEAT = "EXPENSE_PLOICY_PRIORITY_REPEAT";//同一账套下优先级重复

    //报账单类型
    String EXPENSE_REPORT_TYPE_ALREADY_EXISTS = "EXPENSE_REPORT_TYPE_ALREADY_EXISTS";//该报账单类型已经存在！
    String EXPENSE_REPORT_TYPE_NOT_EXIST = "EXPENSE_REPORT_TYPE_NOT_EXIST";//该报账单类型不存在！
    String EXPENSE_REPORT_TYPE_CODE_NOT_ALLOWED_TO_REPEAT = "EXPENSE_REPORT_TYPE_CODE_NOT_ALLOWED_TO_REPEAT";//同一账套下报账单类型代码不可重复！
    //报账单类型关联费用类型
    String EXPENSE_REPORT_TYPE_EXPENSE_TYPE_ALREADY_EXISTS = "EXPENSE_REPORT_TYPE_EXPENSE_TYPE_ALREADY_EXISTS";//该报账单类型关联费用类型已经存在！
    String EXPENSE_REPORT_TYPE_EXPENSE_TYPE_NOT_ALLOWED_TO_REPEAT = "EXPENSE_REPORT_TYPE_EXPENSE_TYPE_NOT_ALLOWED_TO_REPEAT";//该报账单类型关联费用类型重复！
    String EXPENSE_REPORT_TYPE_EXPENSE_TYPE_SHOULD_NOT_EMPTY = "EXPENSE_REPORT_TYPE_EXPENSE_TYPE_SHOULD_NOT_EMPTY";//该报账单类型关联费用类型不能为空！
    //报账单类型关联付款用途
    String EXPENSE_REPORT_TYPE_TRANSACTION_CLASS_ALREADY_EXISTS = "EXPENSE_REPORT_TYPE_TRANSACTION_CLASS_ALREADY_EXISTS";//该报账单类型关联付款用途已经存在！
    String EXPENSE_REPORT_TYPE_TRANSACTION_CLASS_NOT_ALLOWED_TO_REPEAT = "EXPENSE_REPORT_TYPE_TRANSACTION_CLASS_NOT_ALLOWED_TO_REPEAT";//该报账单类型关联付款用途重复！
    String EXPENSE_REPORT_TYPE_TRANSACTION_CLASS_SHOULD_NOT_EMPTY = "EXPENSE_REPORT_TYPE_TRANSACTION_CLASS_SHOULD_NOT_EMPTY";//该报账单类型关联付款用途不能为空！
    //报账单类型关联部门
    String EXPENSE_REPORT_TYPE_DEPARTMENT_ALREADY_EXISTS = "EXPENSE_REPORT_TYPE_DEPARTMENT_ALREADY_EXISTS";//该报账单类型关联部门已经存在！
    String EXPENSE_REPORT_TYPE_DEPARTMENT_NOT_ALLOWED_TO_REPEAT = "EXPENSE_REPORT_TYPE_DEPARTMENT_NOT_ALLOWED_TO_REPEAT";//该报账单类型关联部门重复！
    //报账单类型关联人员组
    String EXPENSE_REPORT_TYPE_USER_GROUP_ALREADY_EXISTS = "EXPENSE_REPORT_TYPE_USER_GROUP_ALREADY_EXISTS";//该报账单类型关联人员组已经存在！
    String EXPENSE_REPORT_TYPE_USER_GROUP_NOT_ALLOWED_TO_REPEAT = "EXPENSE_REPORT_TYPE_USER_GROUP_NOT_ALLOWED_TO_REPEAT";//该报账单类型关联人员组重复！
    //报账单类型关联公司
    String EXPENSE_REPORT_TYPE_COMPANY_ALREADY_EXISTS = "EXPENSE_REPORT_TYPE_COMPANY_ALREADY_EXISTS";//该报账单类型关联公司已经存在！
    String EXPENSE_REPORT_TYPE_COMPANY_NOT_EXIST = "EXPENSE_REPORT_TYPE_COMPANY_NOT_EXIST";//该报账单类型关联公司不存在！
    String EXPENSE_REPORT_TYPE_COMPANY_NOT_ALLOWED_TO_REPEAT = "EXPENSE_REPORT_TYPE_COMPANY_NOT_ALLOWED_TO_REPEAT";//该报账单类型关联公司重复！
    //报账单类型关联维度
    String EXPENSE_REPORT_TYPE_DIMENSION_ALREADY_EXISTS = "EXPENSE_REPORT_TYPE_DIMENSION_ALREADY_EXISTS";//该报账单类型关联维度已经存在！
    String EXPENSE_REPORT_TYPE_DIMENSION_NOT_EXIST = "EXPENSE_REPORT_TYPE_DIMENSION_NOT_EXIST";//该报账单类型关联维度不存在！
    String EXPENSE_REPORT_TYPE_DIMENSION_NOT_ALLOWED_TO_REPEAT = "EXPENSE_REPORT_TYPE_DIMENSION_NOT_ALLOWED_TO_REPEAT";//该报账单类型关联维度类型重复！
    String EXPENSE_REPORT_TYPE_DIMENSION_SEQUENCE_NUMBER_NOT_ALLOWED_TO_REPEAT_AT_THE_SAME_POSITION = "EXPENSE_REPORT_TYPE_DIMENSION_SEQUENCE_NUMBER_NOT_ALLOWED_TO_REPEAT_AT_THE_SAME_POSITION";//该报账单类型关联维度同样布局位置下优先级重复！
    //报账单类型分摊设置
    String EXPENSE_REPORT_TYPE_DIST_SETTING_ALREADY_EXISTS = "EXPENSE_REPORT_TYPE_DIST_SETTING_ALREADY_EXISTS";//该报账单类型分摊设置已经存在！
    String EXPENSE_REPORT_TYPE_DIST_SETTING_NOT_EXIST = "EXPENSE_REPORT_TYPE_DIST_SETTING_NOT_EXIST";//该报账单类型分摊设置不存在！

    //差旅申请单类型
    String EXPENSE_TRAVEL_APPLICATION_TYPE_CODE_REPEAT = "EXPENSE_TRAVEL_APPLICATION_TYPE_CODE_REPEAT";//一个账套下差旅申请单类型代码不可重复！
    String EXPENSE_TRAVEL_APPLICATION_TYPE_NOT_EXISTS = "EXPENSE_TRAVEL_APPLICATION_TYPE_NOT_EXISTS";//差旅申请单类型不存在！
    String EXPENSE_TRAVEL_APPLICATION_TYPE_ASSIGN_COMPANY_REPEAT = "EXPENSE_TRAVEL_APPLICATION_TYPE_ASSIGN_COMPANY_REPEAT";//差旅申请单类型关联公司重复！
    String EXPENSE_TRAVEL_APPLICATION_TYPE_ASSIGN_COMPANY_NOT_EXISTS = "EXPENSE_TRAVEL_APPLICATION_TYPE_ASSIGN_COMPANY_NOT_EXISTS";//差旅申请单类型关联公司不存在！
    String EXPENSE_TRAVEL_APPLICATION_TYPE_ASSIGN_DIMENSION_REPEAT = "EXPENSE_TRAVEL_APPLICATION_TYPE_ASSIGN_DIMENSION_REPEAT";//差旅申请单类型分配的维度或者优先级不允许重复！
    String EXPENSE_TRAVEL_APPLICATION_TYPE_ASSIGN_COMPANY_IS_NULL = "EXPENSE_TRAVEL_APPLICATION_TYPE_ASSIGN_COMPANY_IS_NULL";//差旅申请单类型关联公司为空！

    /**
     * 对公报账维护相关错误
     */
    //报账类型不允许为空！
    String EXPENSE_REPORT_TYPE_IS_NUTT = "EXPENSE_REPORT_TYPE_IS_NUTT";
    //{0}单据不能删除！
    String EXPENSE_REPORT_CANNOT_DELETED = "EXPENSE_REPORT_CANNOT_DELETED";
    //报账单头信息不存在！
    String EXPENSE_REPORT_HEADER_IS_NUTT = "EXPENSE_REPORT_HEADER_IS_NUTT";
    // 报账单行单价和数量不允许为空！
    String EXPENSE_REPORT_LINE_PRICE_IS_NULL = "EXPENSE_REPORT_LINE_PRICE_IS_NULL";
    //收款方信息不完整
    String EXPENSE_REPORT_ACCOUNT_INFO_IS_NOT_COMPLETE = "EXPENSE_REPORT_ACCOUNT_INFO_IS_NOT_COMPLETE";
    //合同信息不能为空
    String EXPENSE_REPORT_CONTRACT_IS_NULL = "EXPENSE_REPORT_CONTRACT_IS_NULL";
    //付款行金额超出合同计划行金额!
    String EXPENSE_REPORT_PAYMENT_SCHEDULE_AMOUT_TOO_MUCH = "EXPENSE_REPORT_PAYMENT_SCHEDULE_AMOUT_TOO_MUCH";
    //付款行付款用途不能为空！
    String EXPENSE_REPORT_PAYMENT_SCHEDULE_CSH_TRANSACTION_NULL = "EXPENSE_REPORT_PAYMENT_SCHEDULE_CSH_TRANSACTION_NULL";
    //该计划付款行不存在
    String EXPENSE_REPORT_PAYMENT_SCHEDULE_IS_NULL = "EXPENSE_REPORT_PAYMENT_SCHEDULE_IS_NULL";
    //该费用行不存在
    String EXPENSE_REPORT_LINE_IS_NULL = "EXPENSE_REPORT_LINE_IS_NULL";
    //付款行金额超出单据金额!
    String EXPENSE_REPORT_PAYMENT_SCHEDULE_AMOUT_GREATER_DOCUMENT_AMOUNT = "EXPENSE_REPORT_PAYMENT_SCHEDULE_AMOUT_GREATER_DOCUMENT_AMOUNT";
    // 单据状态不允许进行此处操作，请检查单据状态！
    String EXPENSE_REPORT_STATUS_ERROR = "EXPENSE_REPORT_STATUS_ERROR";
    // 费用行金额合计不等于分摊行金额！
    String EXPENSE_REPORT_LINE_AMOUNT_UNEQUAL_DIST_AMOUNT = "EXPENSE_REPORT_LINE_AMOUNT_UNEQUAL_DIST_AMOUNT";
    //请维护计划付款行信息
    String EXPENSE_REPORT_SCHEDULE_NOT_NULL = "EXPENSE_REPORT_SCHEDULE_NOT_NULL";
    //单据关联的合同{0}处于{1}状态，无法关联
    String EXPENSE_REPORT_CONTRACT_STATUS = "EXPENSE_REPORT_CONTRACT_STATUS";
    String CONTRACT_STATUS_HOLD = "contract.status.hold";//暂挂
    String CONTRACT_STATUS_CANCEL = "contract.status.cancel";//取消
    String CONTRACT_STATUS_FINISH = "contract.status.finish";//完成
    String EXPENSE_REPORT_SCHEDULE_TOTAL_AMOUNT_ERROR = "EXPENSE_REPORT_SCHEDULE_TOTAL_AMOUNT_ERROR";//计划付款行总金额必须等于报账单总金额
    String EXPENSE_REPORT_PAYMENT_INFO_ERROR = "EXPENSE_REPORT_PAYMENT_INFO_ERROR";//该计划付款行信息不完整
    String EXPENSE_REPORT_LINE_AMOUNT_TOO_BIG = "EXPENSE_REPORT_LINE_AMOUNT_TOO_BIG";//费用行金额大于申请单行可关联金额
    /**
     * 分摊行XX字段需参与分摊，不可为空，请检查该报账单类型分摊设置！
     */
    String EXPENSE_REPORT_DIST_REQUIRED_FIELD_NONE = "EXPENSE_REPORT_DIST_REQUIRED_FIELD_NONE";
    /**
     * 公司
     */
    String EXPENSE_REPORT_DIST_COMPANY = "expense.report.company";
    /**
     * 部门
     */
    String EXPENSE_REPORT_DIST_DEPARTMENT = "expense.report.department";
    /**
     * 责任中心
     */
    String EXPENSE_REPORT_DIST_REST_CENTER = "expense.report.responsibility.center";
    /**
     * 请维护费用行信息
     */
    String EXPENSE_REPORT_LINE_NOT_NULL = "EXPENSE_REPORT_LINE_NOT_NULL";
    /**
     * 请维护分摊行信息
     */
    String EXPENSE_REPORT_DIST_NOT_NULL = "EXPENSE_REPORT_DIST_NOT_NULL";
    /**
     * 分摊行总金额必须等于费用行金额
     */
    String EXPENSE_REPORT_DIST_TOTAL_AMOUNT_ERROR = "EXPENSE_REPORT_DIST_TOTAL_AMOUNT_ERROR";

    //已有差旅类的申请大类!
    String EXPENSE_EXPENSE_TYPE_CATEGORY_ALREADY_EXIST_TRAVEL_TYPE = "EXPENSE_EXPENSE_TYPE_CATEGORY_ALREADY_EXIST_TRAVEL_TYPE";

    //读取文件失败
    String READ_FILE_FAILED = "READ_FILE_FAILED";

    /**
     * AuditFlag审批标志-审批中
     */
    String EXPENSE_REPORT_DIST_APPROVING = "expense.report.approving";

    /**
     * AuditFlag审批标志-审核通过
     */
    String EXPENSE_REPORT_DIST_APPROVED = "expense.report.approved";

    /**
     * ReverseFlag反冲标志-未反冲
     */
    String EXPENSE_REPORT_DIST_NOT_REVERSE = "expense.report.not.reverse";

    /**
     * ReverseFlag反冲标志-已反冲
     */
    String EXPENSE_REPORT_DIST_REVERSED = "expense.report.reversed";

    /**
     * ReverseFlag反冲标志-反冲提交未审批
     */
    String EXPENSE_REPORT_DIST_NOT_APPROVE = "expense.report.not.approve";

    /**
     * 进项税提交校验行信息
     */
    String EXPENSE_INPUT_TAX_TRANSFER_AMOUNT_NOT_ENOUGH = "EXPENSE_INPUT_TAX_TRANSFER_AMOUNT_NOT_ENOUGH";

    /**
     * 申请总金额不可大于关联合同总金额，请修改金额！
     */
    String EXPENSE_APPLICATION_AMOUNT_MUST_LESS_THEN_CONTRACT_AMOUNT = "EXPENSE_APPLICATION_AMOUNT_MUST_LESS_THEN_CONTRACT_AMOUNT";
    /**
     * 预付款金额不可大于申请总金额，请修改金额！
     */
    String EXPENSE_PREPAYMENT_AMOUNT_MUST_LESS_THEN_APPLICATION_AMOUNT = "EXPENSE_PREPAYMENT_AMOUNT_MUST_LESS_THEN_APPLICATION_AMOUNT";

    /**
     * 请选择相同币种进行报销！
     */
    String EXPENSE_REPORT_AUTO_CREATE_CURRENCY_ERROR = "EXPENSE_REPORT_AUTO_CREATE_CURRENCY_ERROR";

    /**
     * 录入发票（发票代码: {0},发票号码: {1}）与员工{2}录入的发票重复,请检查发票信息重新录入！
     */
    String EXPENSE_REPORT_INVOICE_EXISTS = "EXPENSE_REPORT_INVOICE_EXISTS";
    /**
     * 录入发票（发票代码: {0},发票号码: {1}）与{2}连号,请确认是否继续使用！
     */
    String EXPENSE_REPORT_INVOICE_CONTINUATION = "EXPENSE_REPORT_INVOICE_CONTINUATION";
    /**
     * 员工{0}录入的发票（发票代码：{1}，发票号码：{2}）
     */
    String EXPENSE_REPORT_INVOICE_CONTINUATION_ASSEMBLY = "EXPENSE_REPORT_INVOICE_CONTINUATION_ASSEMBLY";

    /**
     * 该账本已被报账单关联，不能删除！
     */
    String EXPENSE_REPORT_BOOK_USED = "EXPENSE_REPORT_BOOK_USED";

    /**
     * 该发票已被报账单关联，不能删除！
     */
    String EXPENSE_INVOICE_HEAD_USED ="EXPENSE_INVOICE_HEAD_USED";

    /**
     * 根据发票类型编码获取发票类型信息失败！
     */
    String INVOICE_CHECK_QUERY_INVOICETYPE_ERROR ="INVOICE_CHECK_QUERY_INVOICETYPE_ERROR";

    /**
     * 发票类型ID或发票类型编码必须有一个存在！
     */
    String INVOICE_CHECK_INVOICE_TYPE_ID_OR_CODE_ISNULL ="INVOICE_CHECK_INVOICE_TYPE_ID_OR_CODE_ISNULL";

}
