package com.hand.hcf.app.base.util;

/**
 * Created by houyin.zhang@hand-china.com on 2018/8/13.
 */
public interface RespCode {
    String SYS_ROLE_CODE_NULL = "SYS_ROLE_CODE_NULL";//角色代码不允许为空
    String SYS_ROLE_NAME_NULL = "SYS_ROLE_NAME_NULL";// 角色名称不允许为空
    String SYS_CODE_NOT_UNION_IN_TENANT = "SYS_CODE_NOT_UNION_IN_TENANT";// 当前租户已存在该角色代码
    String SYS_ID_NULL = "SYS_ID_NULL"; //id 不应该为空!
    String SYS_ID_NOT_NULL = "SYS_ID_NOT_NULL"; //ID 应该为空
    String SYS_DB_NOT_EXISTS = "SYS_DB_NOT_EXISTS"; //数据库不存在

    String AUTH_MENU_CODE_NULL = "AUTH_MENU_CODE_NULL";//菜单代码不允许为空
    String AUTH_MENU_NAME_NULL = "AUTH_MENU_NAME_NULL";// 菜单名称不允许为空
    String AUTH_CODE_NOT_UNION = "AUTH_CODE_NOT_UNION";// 菜单代码已经存在
    String AUTH_HAVING_CHILD_MENU = "AUTH_HAVING_CHILD_MENU";// 菜单代码已经存在
    String AUTH_MENU_FUNCTION_PARENT_MUST_BE_CATALOG = "AUTH_MENU_FUNCTION_PARENT_MUST_BE_CATALOG";// 功能的上级菜单必须是目录
    String AUTH_MENU_PARENT_CATALOG_ERROR = "AUTH_MENU_PARENT_CATALOG_ERROR";//功能只能添加到最底级的目录
    String AUTH_ROOT_CATALOG_MUST_BE_CATALOG = "AUTH_ROOT_CATALOG_MUST_BE_CATALOG";//功能只能添加到最底级的目录
    String AUTH_HAS_CHILD_CATALOG_CAN_NOT_BE_FUNCTION = "AUTH_HAS_CHILD_CATALOG_CAN_NOT_BE_FUNCTION";//当前菜单存在子目录，不允许由目录变更为功能

    String AUTH_USER_ROLE_EXISTS = "AUTH_USER_ROLE_EXISTS"; // 用户角色组合已经存在
    String AUTH_ROLE_MENU_EXISTS = "AUTH_ROLE_MENU_EXISTS"; // 角色菜单组合已经存在

    String AUTH_BUTTON_CODE_NULL = "AUTH_BUTTON_CODE_NULL";//按钮代码不允许为空
    String AUTH_BUTTON_CODE_NOT_UNION = "AUTH_BUTTON_CODE_NOT_UNION";// 按钮代码在菜单中已经存在
    String AUTH_BUTTON_NAME_NULL = "AUTH_BUTTON_NAME_NULL";//按钮名称不允许为空

    String AUTH_ROLE_MENU_BUTTON_EXISTS = "AUTH_ROLE_MENU_BUTTON_EXISTS"; // 角色菜单按钮组合已经存在

    String AUTH_COMPONENT_NAME_NULL = "AUTH_COMPONENT_NAME_NULL";// 组件名称不允许为空
    String AUTH_COMPONENT_TYPE_INVALID = "AUTH_COMPONENT_TYPE_INVALID";// 组件类型值无效,只能为1或2.

    String AUTH_MODULE_CODE_NULL = "AUTH_MODULE_CODE_NULL";// 模块代码不允许为空
    String AUTH_MODULE_NAME_NULL = "AUTH_MODULE_NAME_NULL";// 模块名称不允许为空
    String AUTH_MODULE_CODE_NOT_UNION = "AUTH_MODULE_CODE_NOT_UNION";// 模块代码已经存在

    String AUTH_FRONT_KEY_NULL = "AUTH_FRONT_KEY_NULL";// Key不允许为空
    String AUTH_MODULE_ID_NULL = "AUTH_MODULE_ID_NULL";// 必须关联模块
    String AUTH_FRONT_KEY_NOT_UNION = "AUTH_FRONT_KEY_NOT_UNION";// KEY必须唯一

    String AUTH_REQUEST_CODE_NULL = "AUTH_REQUEST_CODE_NULL";// 请求名称不允许为空
    String AUTH_REQUEST_INTERFACE_NULL = "AUTH_REQUEST_INTERFACE_NULL";// 请求必须关联接口

    String AUTH_RESPONSE_CODE_NULL = "AUTH_RESPONSE_CODE_NULL";// 响应名称不允许为空
    String AUTH_RESPONSE_INTERFACE_NULL = "AUTH_RESPONSE_INTERFACE_NULL";// 响应必须关联接口

    String AUTH_LANGUAGE_CODE_NULL = "AUTH_LANGUAGE_CODE_NULL";// 语言代码不允许为空
    String AUTH_LANGUAGE_NAME_NULL = "AUTH_LANGUAGE_NAME_NULL";// 语言名称不允许为空
    String AUTH_LANGUAGE_CODE_NOT_UNION = "AUTH_LANGUAGE_CODE_NOT_UNION";// 语言代码已经存在

    String AUTH_ERROR_CODE_NULL = "AUTH_ERROR_CODE_NULL";// 报错代码不允许为空
    String AUTH_ERROR_MESSAGE_NULL = "AUTH_ERROR_MESSAGE_NULL";// 报错代码不允许为空

    //数据权限
    String AUTH_DATA_AUTHORITY_CITED = "AUTH_DATA_AUTHORITY_CITED";        //该数据权限已被引用，不可删除！
    String AUTH_DATA_AUTHORITY_RULE_EXISTS = "AUTH_DATA_AUTHORITY_RULE_EXISTS";  //同一权限下，规则名称不能重复！
    String AUTH_DATA_AUTHORITY_RULE_DETAIL_VALUE_NONE = "AUTH_DATA_AUTHORITY_RULE_DETAIL_VALUE_NONE";   //数据权限为手工选择时，请至少选择一条数据！
    String AUTH_DATA_AUTHORITY_RULE_DETAIL_EXISTS = "AUTH_DATA_AUTHORITY_RULE_DETAIL_EXISTS";   //数据权限规则数据类型已存在，请勿重复保存！
    String AUTH_DATA_AUTHORITY_EXISTS = "AUTH_DATA_AUTHORITY_EXISTS";   //数据权限已存在，请勿重复保存！

    //数据权限参数配置
    String AUTH_DATA_AUTH_TABLE_PROPERTY_DATA_TYPE_EXISTS = "AUTH_DATA_AUTH_TABLE_PROPERTY_DATA_TYPE_EXISTS";//此参数类型在该表名下已经存在!
    String AUTH_DATA_AUTH_TABLE_PROPERTY_COLUMN_NAME_EXISTS = "AUTH_DATA_AUTH_TABLE_PROPERTY_COLUMN_NAME_EXISTS";//此参数名称在该表名下已经存在!
}
