package com.hand.hcf.app.core.util;

public interface RespCode {

    /** 失败 */
    String SYS_FAILED = "SYS_FAILED";
    /** 成功 */
    String SYS_SUCCESS = "SYS_SUCCESS";
    /*通用*/
    String SYS_STRING_IS_NULL="SYS_STRING_IS_NULL"; //格式化string为空
    String SYS_DATE_FORMAT_NOT_TRUE="SYS_DATE_FORMAT_NOT_TRUE";//格式不正确
	String SYS_OPERATION_DATA_NOT_BE_EMPTY = "SYS_OPERATION_DATA_NOT_BE_EMPTY";  //参与运算的数据不能为空
    String SYS_VERSION_NUMBER_CHANGED = "SYS_VERSION_NUMBER_CHANGED";   //版本号不一致

    /**
     * 请求正在处理中，请稍后再试
     */
    String SYS_REQUEST_BE_PROCESSING= "SYS_REQUEST_BE_PROCESSING";
    /**
     * 请求速度过快!
     */
    String SYS_REQUEST_SPEED_IS_TOO_FAST = "SYS_REQUEST_SPEED_IS_TOO_FAST";
    /** 获取资源失败，请求超时! */
    String SYS_FAILED_TO_GET_RESOURCE_REQUEST_TIMEOUT = "SYS_FAILED_TO_GET_RESOURCE_REQUEST_TIMEOUT";

    String SYS_REFLECT_EXECUTE_GET_SET_FAIL = "SYS_REFLECT_EXECUTE_GET_SET_FAIL";      //利用反射执行get&set方法失败！

    //数据权限错误！解析数据权限标识失败
    String SYS_DATA_AUTHORITY_ANALYSIS_ERROR = "SYS_DATA_AUTHORITY_ANALYSIS_ERROR";
    //数据权限错误！请配置数据权限表名
    String SYS_DATA_AUTHORITY_TABLE_EMPTY = "SYS_DATA_AUTHORITY_TABLE_EMPTY";
    //数据权限错误！未匹配到表名:{0}
    String SYS_DATA_AUTHORITY_TABLE_NOT_FOUND = "SYS_DATA_AUTHORITY_TABLE_NOT_FOUND";
    //数据权限错误！数据类型{0}未获取到列值范围
    String SYS_DATA_AUTHORITY_COLUMN_VALUES_EMPTY = "SYS_DATA_AUTHORITY_COLUMN_VALUES_EMPTY";
    //数据权限错误！筛选方式为自定义sql时，必须指定表别名
    String SYS_DATA_AUTHORITY_RELATED_TABLE_ALIAS_EMPTY = "SYS_DATA_AUTHORITY_RELATED_TABLE_ALIAS_EMPTY";
    //数据类型{0}未匹配到列信息配置！
    String SYS_DATA_AUTHORITY_COLUMN_PROPERTIES_NONE = "SYS_DATA_AUTHORITY_COLUMN_PROPERTIES_NONE";
    //数据类型{0}对应列配置信息错误！
    String SYS_DATA_AUTHORITY_COLUMN_PROPERTIES_ERROR = "SYS_DATA_AUTHORITY_COLUMN_PROPERTIES_ERROR";
    //数据权限只支持列筛选及自定义sql两种方式！
    String SYS_DATA_AUTHORITY_DATA_TYPE_ERROR = "SYS_DATA_AUTHORITY_DATA_TYPE_ERROR";
    // 数据权限错误！查询语句只能指定一张主表！
    String DATA_AUTHORITY_LABEL_TOO_MUCH = "DATA_AUTHORITY_LABEL_TOO_MUCH";


    //导入失败，获取实体类实例失败！
    String SYS_EXCEL_IMPORT_GET_ENTITY_INSTANCE_FAILED = "SYS_EXCEL_IMPORT_GET_ENTITY_INSTANCE_FAILED";
    //导入失败，初始化列信息失败！
    String SYS_EXCEL_IMPORT_ROW_COLUMN_ERROR = "SYS_EXCEL_IMPORT_ROW_COLUMN_ERROR";
    //导入失败，序号列不存在！
    String SYS_EXCEL_IMPORT_ROW_NUMBER_COLUMN_EMPTY = "SYS_EXCEL_IMPORT_ROW_NUMBER_COLUMN_EMPTY";
    //导入失败，{0}行序号列不能为空！
    String SYS_EXCEL_IMPORT_ROW_NUMBER_NONE = "SYS_EXCEL_IMPORT_ROW_NUMBER_NONE";
    //导入失败，{0}行不能为空！
    String SYS_EXCEL_IMPORT_COLUMN_NONE = "SYS_EXCEL_IMPORT_COLUMN_NONE";
    //导入失败，{0}行序号必须为数字！
    String SYS_EXCEL_IMPORT_ROW_NUMBER_MUST_NUMBER = "SYS_EXCEL_IMPORT_ROW_NUMBER_MUST_NUMBER";
    //导入失败，序号不能重复！
    String SYS_EXCEL_IMPORT_ROW_NUMBER_UNIQUE = "SYS_EXCEL_IMPORT_ROW_NUMBER_UNIQUE";

    //导出的配置信息不能为空！
    String SYS_EXCEL_EXPORT_CONFIG_IS_NULL = "SYS_EXCEL_EXPORT_CONFIG_IS_NULL";
    //需要导出的对象信息不能为空！
    String SYS_EXCEL_EXPORT_GET_ENTITY_INSTANCE_FAILED = "SYS_EXCEL_EXPORT_GET_ENTITY_INSTANCE_FAILED";
    //Excel导出时发生未知异常！
    String SYS_EXCEL_EXPORT_SYSTEM_ERROR = "SYS_EXCEL_EXPORT_SYSTEM_ERROR";
}
